apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: sample-app-pod
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: sample-app-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-app-pod
        owner: siarheisvila
    spec:
      containers:
        - name: sample-container
          image: siarheisvila/sample-application:1.0.0
          ports:
            - containerPort: 8080